In [1]:
import pandas as pd
import numpy as np

In [2]:
'''
1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series
	Values
	Index
	Data type
	Mean
	Maximum
	Minimum
'''

x = pd.Series([78, 85, 92, 67, 88])
print("Complete Series:\n", x)

print("\nValues: ", x.values)

print("\nIndex: ", x.index)

print("\nData type: ", x.dtype)

print("\nMean: ", x.mean())

print("\nMaximum: ", x.max())

print("\nMinimum: ", x.min())

Complete Series:
 0    78
1    85
2    92
3    67
4    88
dtype: int64

Values:  [78 85 92 67 88]

Index:  RangeIndex(start=0, stop=5, step=1)

Data type:  int64

Mean:  82.0

Maximum:  92

Minimum:  67

In [3]:
''' 
2. Create a Series containing:
 
   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
	Display the marks of Meena.
'''
Student= ['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun']
Marks = [85, 78, 92, 74, 88]

df = pd.Series(Marks, index=Student)
df['Meena']

np.int64(92)

In [4]:
""" 
3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types
"""

data = {
    'Name':['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
    'Age': [22,23,21,24,22],
    'Department':['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Marks':[85,78,92,74,88]
}

students = pd.DataFrame(data)
print("Complete DataFame\n",students)
print('\nFirst 3 rows\n',students.head(3))
print('\nLast 2 rows\n',students.tail(2))
print('\nShape\n',students.shape)
print('\nColumns\n',students.columns)
print('\nData Types\n',students.dtypes)

Complete DataFame
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows
     Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape
 (5, 4)

Columns
 Index(['Name', 'Age', 'Department', 'Marks'], dtype='str')

Data Types
 Name            str
Age           int64
Department      str
Marks         int64
dtype: object

In [5]:
''' 
4. Using the previous DataFrame, display:

	info()
	describe()
	Number of rows
	Number of columns
'''
print('\nFifo\n',students.info())
print('\ndescribe\n',students.describe())
print('\nNumbers of rows\n',students.shape[0])
print('\nNumbers of columns\n',students.shape[1])

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Marks       5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

Fifo
 None

describe
              Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Numbers of rows
 5

Numbers of columns
 4

In [6]:
''' 
5. Using df, display:

	Name column
	Marks column
	Name and Marks together
'''
print('\nName Column\n',students['Name'])
print('\nMarks Column\n',students['Marks'])
print('\nName and Marks Column\n',students[['Name','Marks']])

Name Column
 0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: str

Marks Column
 0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

Name and Marks Column
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [7]:
''' 
6. Display:

	First row using iloc
	Third row using iloc
	Rows 1 to 3
	Name and Marks columns using loc
'''

print('\nFirst row using iloc\n',students.iloc[0])
print('\nThird row using iloc\n',students.iloc[3])
print('\nFirst to Third rows using iloc\n',students.iloc[:3])
print('\nName and Marks columns using loc\n',students.loc[:, ['Name', 'Marks']])

First row using iloc
 Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

Third row using iloc
 Name          Kiran
Age              24
Department       ME
Marks            74
Name: 3, dtype: object

First to Third rows using iloc
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Name and Marks columns using loc
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

In [8]:
''' 
7. Find:

	Students scoring above 80.
	Students scoring between 75 and 90.
	Students belonging to CSE.
	CSE students scoring above 80.
'''
print('\nStudents scoring above 80: \n',students[students['Marks']>80])
print(
    '\nStudents scoring between 75 and 90:\n',students[students['Marks'].between(75, 90)]
)
print('\nStudents belonging to CSE: \n',students[students['Department']=='CSE'])
print('\nCSE students scoring above 80: \n',students[(students['Department']=='CSE') & (students['Marks']>80)])

Students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

Students scoring between 75 and 90:
    Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

Students belonging to CSE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

CSE students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

In [9]:
''' 
8. Display students belonging to either CSE or ECE.
'''
print('\nDisplay students belonging to either CSE or ECE:\n',
    students[students['Department'].isin(['CSE', 'ECE'])])

Display students belonging to either CSE or ECE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

In [10]:
''' 
9. Add a new column called Result. Students scoring 75 or above should receive "Pass", otherwise "Fail".
'''
# np.where -> used to create a new column based on a condition. 
# It takes three arguments: the condition, the value to assign if the condition is True,
#  and the value to assign if the condition is False.
students['Result'] = np.where(
    students['Marks'] >= 75,
    'Pass',
    'Fail'
)

print(students)

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

In [11]:
''' 
10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

'''
# pd.cut -> used to segment and sort data values into bins.
bins = [0, 70, 80, 90, 100]
labels = ['D', 'C', 'B', 'A']
students['Grade'] = pd.cut(students['Marks'], bins=bins, labels=labels, right=False)
print(students)

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

In [12]:
''' 
11. Sort students:

	By marks in ascending order.
	By marks in descending order.
	By Department and then Marks.
'''
print('\nBy marks in ascending order:\n',students.sort_values('Marks'))
print('\nBy marks in descending order:\n',students.sort_values('Marks', ascending=False))
print('\nBy Department and then Marks:\n',students.sort_values(['Department', 'Marks']))

By marks in ascending order:
     Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

By marks in descending order:
     Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

By Department and then Marks:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

In [13]:
''' 
12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:

Missing values
Number of missing values in each column
Rows containing missing values

'''

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

print('\nMissing values:\n',students.isnull())
print('\nNumber of missing values in each column:\n',students.isnull().sum())
print('\nRows containing missing values:\n',students[students.isnull().any(axis=1)])
# any() -> used to check if any element in a DataFrame or Series is True along a specified axis.

Missing values:
     Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values in each column:
 Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:
     Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

In [14]:
''' 
13. Replace:

	Missing Age with average Age
	Missing Marks with average Marks
'''
x = students.copy()

x['Age'] = x['Age'].fillna(students['Age'].mean())
x['Marks'] = x['Marks'].fillna(students['Marks'].mean())
print('\nAfter replacing missing values:\n', x)

After replacing missing values:
     Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

In [15]:
students

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [16]:
''' 
14. Remove rows containing missing values.
'''
y = students.dropna()
print('\nAfter removing rows containing missing values:\n', y)

After removing rows containing missing values:
     Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

In [17]:
''' 
15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

Find duplicates:
Display duplicate rows:
Remove duplicates:

'''
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

print('\nDuplicate rows:\n',df2[df2.duplicated()])
df2.drop_duplicates(inplace=True)
print('\nAfter removing duplicates:\n', df2)

Duplicate rows:
    Name  Marks
3  Asha     85

After removing duplicates:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

In [18]:
''' 
16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean
Median
Maximum
Minimum
Standard deviation
Sum

'''

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

print('\nMean:\n',marks['Marks'].mean())
print('\nMedian:\n',marks['Marks'].median())    
print('\nMaximum:\n',marks['Marks'].max())
print('\nMinimum:\n',marks['Marks'].min())
print('\nStandard deviation:\n',marks['Marks'].std())
print('\nSum:\n',marks['Marks'].sum())

Mean:
 82.0

Median:
 85.0

Maximum:
 92

Minimum:
 67

Standard deviation:
 9.82344135219425

Sum:
 410

In [19]:
''' 
17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department
Maximum marks by department
Number of students in each department

For each department, calculate:
Mean
Minimum
Maximum
Count

'''
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)

x = df.groupby('Department')
print('\nAverage marks by department:\n',x['Marks'].mean())
print('\nMaximum marks by department:\n',x['Marks'].max())
print('\nNumber of students in each department:\n',x.size())
print('\nFor each department, calculate:\n',x['Marks'].agg(['mean', 'min', 'max', 'count']))

Average marks by department:
 Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

Maximum marks by department:
 Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

Number of students in each department:
 Department
CSE    3
ECE    2
ME     1
dtype: int64

For each department, calculate:
                  mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

In [20]:
''' 
18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.


'''
students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

pd.merge(students, marks, on='StudentID', how='inner')

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

In [21]:
""" 
19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

Display the first five records.
Find the dimensions of the dataset.
Find the average final mark.
Find the highest-scoring student.
Find the lowest-scoring student.
Display students scoring above 80.
Find average marks by department.
Find students having attendance above 80%.
Sort students by FinalMarks.
Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
Add a performance category:
	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement
Find the department having the highest average FinalMarks.

"""

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)
print('\nFirst five records:\n',df.head())
print('\nDimensions of the dataset:\n',df.shape)
print('\nAverage final mark:\n',df['FinalMarks'].mean())
print('\nHighest-scoring student:\n',df.loc[df['FinalMarks'].idxmax()])
print('\nLowest-scoring student:\n',df.loc[df['FinalMarks'].idxmin()])
print('\nStudents scoring above 80:\n',df[df['FinalMarks'] > 80])
print('\nAverage marks by department:\n',df.groupby('Department')['FinalMarks'].mean())
print('\nStudents having attendance above 80%:\n',df[df['Attendance'] > 80])
print('\nStudents sorted by FinalMarks:\n',df.sort_values('FinalMarks'))

First five records:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

Dimensions of the dataset:
 (8, 5)

Average final mark:
 81.625

Highest-scoring student:
 Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

Lowest-scoring student:
 Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

Students scoring above 80:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Average marks by department:
 Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

Students having attendance above 80%:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Students sorted by FinalMarks:
     Name Department  Attendance  Internal  FinalMarks
3  Kiran         ME          68        65          62
6   John         ME          72        70          68
1   Ravi        ECE          75        72          74
4   Arun        ECE          82        80          83
0   Asha        CSE          92        85          88
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93
2  Meena        CSE          96        94          96

In [22]:
''' 
20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

Average salary.
Maximum and minimum salary.
Employee receiving the highest salary.
Employees earning above ₹60,000.
Average salary for each department.
Average experience by department.
Number of employees in each department.
Sort employees by salary.
Find IT employees with more than 3 years of experience.
Add a SalaryLevel column:
	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low
'''

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

print('\nAverage salary:\n',employees['Salary'].mean())
print('\nMaximum salary:\n',employees['Salary'].max())
print('\nMinimum salary:\n',employees['Salary'].min())
print('\nEmployee receiving the highest salary:\n',employees.loc[employees['Salary'].idxmax()])
print('\nEmployees earning above ₹60,000:\n',employees[employees['Salary'] > 60000])
dep = employees.groupby('Department')
print('\nAverage salary for each department:\n',dep['Salary'].mean())
print('\nAverage experience by department:\n',dep['Experience'].mean())
print('\nNumber of employees in each department:\n',dep.size())
print('\nEmployees sorted by salary:\n',employees.sort_values('Salary')) 
print('\nIT employees with more than 3 years of experience:\n',employees[(employees['Department']=='IT') & (employees['Experience']>3)])
bins = [0, 50000, 75000, np.inf]
labels = ['Low', 'Medium', 'High']
employees['SalaryLevel'] = pd.cut(employees['Salary'], bins=bins, labels=labels, right=False)
print('\nEmployees with SalaryLevel:\n',employees)

Average salary:
 62875.0

Maximum salary:
 85000

Minimum salary:
 45000

Employee receiving the highest salary:
 Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

Employees earning above ₹60,000:
   Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

Average salary for each department:
 Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

Average experience by department:
 Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

Number of employees in each department:
 Department
Finance    3
HR         2
IT         3
dtype: int64

Employees sorted by salary:
   Employee Department  Experience  Salary
1      E02         HR           3   45000
6      E07         IT           2   48000
4      E05         HR           6   55000
0      E01         IT           5   60000
3      E04    Finance           4   65000
7      E08    Finance           5   70000
2      E03         IT           7   75000
5      E06    Finance           8   85000

IT employees with more than 3 years of experience:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

Employees with SalaryLevel:
   Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium