In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'C:\Users\19286\OneDrive\Desktop\aml lab\20-8-26\bestsellers.csv')
data

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction

In [3]:
data.index

RangeIndex(start=0, stop=550, step=1)

In [4]:
data.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='str')

In [5]:
data.shape

(550, 7)

In [6]:
data.size

3850

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB

In [8]:
data.describe()

       User Rating       Reviews       Price         Year
count   548.000000    549.000000  549.000000   550.000000
mean      4.618066  11958.038251   13.100182  2014.000000
std       0.227341  11741.299889   10.852149     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4028.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17323.000000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [9]:
data

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2019,Non Fiction

In [10]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(X)
print(y)

[['10-Day Green Smoothie Cleanse' 'JJ Smith' 4.7 17350.0 8.0 2016]
 ['11/22/63: A Novel' 'Stephen King' 4.6 2052.0 22.0 2011]
 ['12 Rules for Life: An Antidote to Chaos' 'Jordan B. Peterson' 4.7
  18979.0 15.0 2018]
 ...
 ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life'
  'Jen Sincero' 4.7 14331.0 8.0 2017]
 ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life'
  'Jen Sincero' 4.7 14331.0 8.0 2018]
 ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life'
  'Jen Sincero' 4.7 14331.0 8.0 2019]]
<StringArray>
['Non Fiction',     'Fiction', 'Non Fiction',     'Fiction', 'Non Fiction',
     'Fiction',     'Fiction',     'Fiction', 'Non Fiction',     'Fiction',
 ...
     'Fiction',     'Fiction',     'Fiction',     'Fiction',     'Fiction',
     'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction']
Length: 550, dtype: str

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer = imputer.fit(X[:,1:3])# fit -> perform the operation/learning
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]],
      shape=(550, 6), dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Labelencoder_X = LabelEncoder()
X[:,0] = Labelencoder_X.fit_transform(X[:,0])
print(X)

[[0 'JJ Smith' 4.7 17350.0 8.0 2016]
 [1 'Stephen King' 4.6 2052.0 22.0 2011]
 [2 'Jordan B. Peterson' 4.7 18979.0 15.0 2018]
 ...
 [350 'Jen Sincero' 4.7 14331.0 8.0 2017]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2018]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2019]]

In [13]:
Labelencoder_y = LabelEncoder()
y = Labelencoder_y.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [14]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Genre", OneHotEncoder(), [0,1])], remainder='passthrough')
X = ct.fit_transform(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [16]:
X_train,X_test,y_train,y_test

(<Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 2631 stored elements and shape (440, 603)>,
 <Compressed Sparse Row sparse matrix of dtype 'float64'
 	with 657 stored elements and shape (110, 603)>,
 array([1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1]),
 array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
        0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1]))

In [18]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler(with_mean=False)
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train

array([[200, 'School Zone', 4.8, 23047.0, 6.0, 2018],
       [97, 'Giles Andreae', 4.8, 14038.0, 4.0, 2017],
       [107, 'Margaret Wise Brown', 4.8, 8837.0, 5.0, 2019],
       ...,
       [123, 'J. D. Vance', 4.4, 15526.0, 14.0, 2016],
       [348, 'R. J. Palacio', 4.8, 21625.0, 9.0, 2017],
       [263, 'Rebecca Skloot', 4.7, 9289.0, 9.0, 2012]],
      shape=(440, 6), dtype=object)