In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r'C:\Users\19286\OneDrive\Desktop\aml lab\20-8-26\Groceries_dataset.csv')
data

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [3]:
data.index

RangeIndex(start=0, stop=38765, step=1)

In [4]:
data.columns

Index(['Member_number', 'Date', 'itemDescription'], dtype='str')

In [5]:
data.shape

(38765, 3)

In [6]:
data.size

116295

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  str
 2   itemDescription  38765 non-null  str
dtypes: int64(1), str(2)
memory usage: 908.7 KB

In [8]:
data.describe

<bound method NDFrame.describe of        Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]>

In [9]:
data

       Member_number        Date        itemDescription
0               1808  21-07-2015         tropical fruit
1               2552  05-01-2015             whole milk
2               2300  19-09-2015              pip fruit
3               1187  12-12-2015       other vegetables
4               3037  01-02-2015             whole milk
...              ...         ...                    ...
38760           4471  08-10-2014          sliced cheese
38761           2022  23-02-2014                  candy
38762           1097  16-04-2014               cake bar
38763           1510  03-12-2014  fruit/vegetable juice
38764           1521  26-12-2014               cat food

[38765 rows x 3 columns]

In [10]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print(X)
print(y)

[[1808 '21-07-2015']
 [2552 '05-01-2015']
 [2300 '19-09-2015']
 ...
 [1097 '16-04-2014']
 [1510 '03-12-2014']
 [1521 '26-12-2014']]
<StringArray>
[          'tropical fruit',               'whole milk',
                'pip fruit',         'other vegetables',
               'whole milk',               'rolls/buns',
         'other vegetables',               'pot plants',
               'whole milk',           'tropical fruit',
 ...
            'bottled water',    'fruit/vegetable juice',
               'rolls/buns', 'long life bakery product',
                      'oil',            'sliced cheese',
                    'candy',                 'cake bar',
    'fruit/vegetable juice',                 'cat food']
Length: 38765, dtype: str

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
X

array([[1808, '21-07-2015'],
       [2552, '05-01-2015'],
       [2300, '19-09-2015'],
       ...,
       [1097, '16-04-2014'],
       [1510, '03-12-2014'],
       [1521, '26-12-2014']], shape=(38765, 2), dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Labelencoder_X = LabelEncoder()
X[:,0] = Labelencoder_X.fit_transform(X[:,0])
print(X)

[[786 '21-07-2015']
 [1504 '05-01-2015']
 [1263 '19-09-2015']
 ...
 [93 '16-04-2014']
 [499 '03-12-2014']
 [510 '26-12-2014']]

In [13]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("member_id", OneHotEncoder(sparse_output=False), [0,1])], remainder='passthrough')
X = ct.fit_transform(X)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [15]:
X_train,X_test,y_train,y_test

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(31012, 4626)),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(7753, 4626)),
 <StringArray>
 [            'citrus fruit',            'specialty bar',
                 'chocolate',    'fruit/vegetable juice',
                   'sausage', 'long life bakery product',
           'root vegetables',                'margarine',
                    'yogurt',          'root vegetables',
  ...
             'domestic eggs',    'fruit/vegetable juice',
                 'pip fruit',              'canned beer',
                  'cat food',    'fruit/vegetable juice',
        'whipped/sour cream',               'whole milk',
              'citrus fruit',                'pip fruit']
 Length: 31012, dtype: str,
 <StringArray>
 [       'tropical fruit',            'whole milk',                'yogurt',
                   'beef',         'bottled water',        'pudding powder',
                 'yogurt',       'root vegetables',       'misc. beverages',
                    'oil',
  ...
       'other vegetables',                 'candy',                  'soda',
          'domestic eggs',                'onions',      'specialty cheese',
                   'curd',      'other vegetables',            'rolls/buns',
  'chocolate marshmallow']
 Length: 7753, dtype: str)

In [16]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [17]:
X_train

array([[-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621],
       [-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621],
       [-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621],
       ...,
       [-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621],
       [-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621],
       [-0.01703803, -0.01795995, -0.01269858, ..., -0.03502621,
        -0.0389595 , -0.03502621]], shape=(31012, 4626))